### ISSUE TITLE
material-ui-leaderboard : Update to release METEOR@1.2.0.1 is impossible:

### ISSUE THREAD

**Issue by lc3t35** [meteor/react-packages#111]
````
Update to release METEOR@1.2.0.1 is impossible:
While reading package from `/Users/laurent/dev/meteor/react-packages/examples/material-ui-leaderboard/packages/npm-container`:
package.js:23:7: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.

This project is at the latest release which is compatible with your current package constraints.
=> Errors while upgrading packages:           
                                              
While reading package from `/Users/laurent/dev/meteor/react-packages/examples/material-ui-leaderboard/packages/npm-container`:
package.js:23:7: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.
````
npm-container/package.js should be modified to allow meteor update in material-ui-leaderboard example  : 
````
Package.onUse(function(api) {
  api.add_files('index.js', 'server');
  api.addAssets('../../packages.json', 'server');
});
````

**Comment by elie222** [comment]
I had a similar problem and this fixed it for me:

From https://forums.meteor.com/t/public-release-candidate-of-meteor-1-2/8986/77
```
If anyone having issues with meteorhacks:npm. Follow these steps:

rm -rf packages/npm-container
meteor remove npm-container
meteor update meteorhacks:npm
meteor
Read More: https://github.com/meteorhacks/npm/issues/95#issuecomment-1376135579
```

**Comment by jonas28** [comment]
I have the same problem as @lc3t35. The solution of @elie222 didn´t work for me. After trying it, i got the following message:

```
=> Started MongoDB.                           
npm-container: updating npm dependencies -- material-ui, externalify, react-tap-event-plugin...
=> Errors prevented startup:                  
   
   While building package npm-container:
   error: couldn't run `npm shrinkwrap`: Command failed: npm ERR! Error: Problems were encountered
   ...
```

**Comment by rogchap** [comment]
Also trying to update my react/meteor app to 1.2 so I've tried to build the material-ui example here but getting this error after updating to 1.2:

```
While building package npm-container:
error: couldn't install npm package material-ui@0.10.1: Command failed: npm ERR! peerinvalid The package react does not satisfy its
siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer material-ui@0.10.1 wants react@>=0.13
npm ERR! peerinvalid Peer react-tap-event-plugin@0.2.0 wants react@^0.14.0-0
```

**Comment by payner35** [comment]
@rogchap this has now been fixed with the update to 

"material-ui": "0.12.0",

https://github.com/callemall/material-ui/pull/1714

**Comment by payner35** [comment]
i now have

```
   building package npm-container:
   error: couldn't run `npm shrinkwrap`: Command failed: npm ERR! Error: Problems were encountered
   npm ERR! Please correct and try again.
   npm ERR! extraneous: fbjs@0.2.1 /Users/gavin/Dropbox/git/SONIK_PRO/sonikRClient/packages/npm-container/.npm/package-new-zm4itw/node_modules/fbjs
   npm ERR! extraneous: react-dom@0.14.0-rc1
 ```

**Comment by rogchap** [comment]
@payner35 I don't think this is specific to material-ul, but rather the `peerDependencies`  that are present in packages. 
The fix you mention is to do with the dependency within `react-tap-event-plugin` for react v0.14+ (which is not released yet)

In Meteor react is loaded via a meteor package, where normally react would be loaded via npm, therefore when we install a react npm package it can't find the dependency on react.

I did get this working by adding react to my `packages.json` file, and then use `externalify` to select the Meteor loaded version of react.

Doing this though, means react is "downloaded" twice... not so good.

**Comment by stubailo** [comment]
Updated the example apps to Meteor 1.2.0.2!

**Comment by rkstar** [comment]
i'm trying to get v0.12.1 to work with meteor 1.2.0.2, but i'm getting package errors, then peerdependencies errors, and now styling errors... 

can someone please explain this with some code?  i'm getting errors all over and i can't seem to figure out wtf i'm doing wrong here:

packages.json:
```
 {
 "externalify": "0.1.0",
  "material-ui": "0.12.1",
  "react": "0.14.0-rc1"
}
```

browserify.options.json
```
{
  "transforms": {
    "externalify": {
      "global": true,
      "external": {
        "react": "Package['react-runtime'].React.require"
      }
    }
  }
}
```

browserify.js
```
injectTapEventPlugin = require("react-tap-event-plugin")
// Needed for onTouchTap
injectTapEventPlugin()
React.initializeTouchEvents(true)

// material ui
mui = require('material-ui')

ThemeManager = new mui.Styles.ThemeManager()
ThemeManager.setTheme(ThemeManager.types.LIGHT)
```

**i know that my ThemeManager setup is wrong...*** but i can't figure out from the MUI docs how to make this work with meteor.  @stubailo are the example apps working with [material-ui 0.12.1](https://github.com/callemall/material-ui) ?

------
current error:
```
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.                    
                                              
events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: Unexpected token (4:62) while parsing /Users/rkstar/dev/projects/wacoosta/packages/npm-container/.npm/package/node_modules/material-ui/lib/app-canvas.js while parsing file: /Users/rkstar/dev/projects/wacoosta/packages/npm-container/.npm/package/node_modules/material-ui/lib/app-canvas.js
  at DestroyableTransform.end [as _flush] (/Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/insert-module-globals/index.js:79:21)
  at DestroyableTransform.<anonymous> (/Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
  at DestroyableTransform.g (events.js:180:16)
  at DestroyableTransform.emit (events.js:92:17)
  at prefinish (/Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:450:12)
  at finishMaybe (/Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:458:7)
  at endWritable (/Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:469:3)
  at DestroyableTransform.Writable.end (/Users/rkstar/.meteor/packages/cosmos_browserify/.0.7.0.1pwzdl1++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:436:5)
  at StringTransform.onend (_stream_readable.js:502:10)
  at StringTransform.g (events.js:180:16)
  at StringTransform.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:448:13)
```

previously i was getting errors about `fbjs@^0.2.0` .... those have gone away after i changes the `browserify.options.json` file to use  `"react: Package[react-runtime].React.require` 

please help.  i'm pretty lost right now.

**Comment by stubailo** [comment]
Can you start a separate issue for this? This issue was just about the example not working with meteor 1.2.

**Comment by rkstar** [comment]
FYI -- i figured out the problem and posted a repo [meteor-material-ui-example](https://github.com/rkstar/meteor-material-ui-example)

**Comment by otroboe** [comment]
@rkstar Thx, your configuration works great !
