### ISSUE TITLE
bug after installing react on Meteor 1.4.1.1

### ISSUE THREAD

**Issue by hackpiro** [meteor/react-packages#199]
after installed the package the console log return this code
how can I fix it?

```
I20160915-17:27:56.255(2)? [Error: Can't find npm module 'react-addons-transition-group/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:27:56.257(2)? [Error: Can't find npm module 'react-addons-css-transition-group/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:27:56.258(2)? [Error: Can't find npm module 'react-addons-linked-state-mixin/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:27:56.259(2)? [Error: Can't find npm module 'react-addons-create-fragment/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:27:56.260(2)? [Error: Can't find npm module 'react-addons-update/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:27:56.260(2)? [Error: Can't find npm module 'react-addons-pure-render-mixin/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:27:56.261(2)? [Error: Can't find npm module 'react-addons-test-utils/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160915-17:27:56.262(2)? [Error: Can't find npm module 'react-addons-perf/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
W20160915-17:27:56.263(2)? (STDERR) WARNING: npm peer requirements (for react-runtime) not installed:
W20160915-17:27:56.264(2)? (STDERR)  - react-addons-transition-group@15.x not installed.
W20160915-17:27:56.264(2)? (STDERR)  - react-addons-css-transition-group@15.x not installed.
W20160915-17:27:56.264(2)? (STDERR)  - react-addons-linked-state-mixin@15.x not installed.
W20160915-17:27:56.265(2)? (STDERR)  - react-addons-create-fragment@15.x not installed.
W20160915-17:27:56.265(2)? (STDERR)  - react-addons-update@15.x not installed.
W20160915-17:27:56.266(2)? (STDERR)  - react-addons-pure-render-mixin@15.x not installed.
W20160915-17:27:56.266(2)? (STDERR)  - react-addons-test-utils@15.x not installed.
W20160915-17:27:56.266(2)? (STDERR)  - react-addons-perf@15.x not installed.
W20160915-17:27:56.266(2)? (STDERR) 
W20160915-17:27:56.267(2)? (STDERR) Read more about installing npm peer dependencies:
W20160915-17:27:56.267(2)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160915-17:27:56.267(2)? (STDERR) 
W20160915-17:27:56.513(2)? (STDERR) /Users/ortiz/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160915-17:27:56.514(2)? (STDERR)                         throw(ex);
W20160915-17:27:56.514(2)? (STDERR)                         ^
W20160915-17:27:56.514(2)? (STDERR) 
W20160915-17:27:56.515(2)? (STDERR) Error: Can't find npm module 'react-addons-transition-group'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160915-17:27:56.515(2)? (STDERR)     at Object.Npm.require (/Users/ortiz/Siti/tutorial/meteor/react/flowrouter/.meteor/local/build/programs/server/boot.js:198:17)
W20160915-17:27:56.515(2)? (STDERR)     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
W20160915-17:27:56.515(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:88:1)
W20160915-17:27:56.516(2)? (STDERR)     at meteorInstall.node_modules.meteor.react-runtime.react-runtime.js (packages/react-runtime/react-runtime.js:29:20)
W20160915-17:27:56.517(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160915-17:27:56.517(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160915-17:27:56.517(2)? (STDERR)     at /Users/ortiz/Siti/tutorial/meteor/react/flowrouter/.meteor/local/build/programs/server/packages/react-runtime.js:79:15
W20160915-17:27:56.517(2)? (STDERR)     at /Users/ortiz/Siti/tutorial/meteor/react/flowrouter/.meteor/local/build/programs/server/packages/react-runtime.js:92:3
W20160915-17:27:56.517(2)? (STDERR)     at /Users/ortiz/Siti/tutorial/meteor/react/flowrouter/.meteor/local/build/programs/server/boot.js:292:10
W20160915-17:27:56.518(2)? (STDERR)     at Array.forEach (native)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by jibe0123** [comment]
I have th same issue

**Comment by ramintagizade** [comment]
Try this : 
meteor npm install --save react react-dom react-addons-transition-group
react-addons-css-transition-group react-addons-linked-state-mixin react-addons-create-fragment react-addons-update react-addons-pure-render-mixin react-addons-test-utils react-addons-perf

**Comment by StorytellerCZ** [comment]
Are you installing the atmosphere react package or installing react from npm? You should install react from npm as described in the [guide](https://guide.meteor.com/react.html).

**Comment by filipenevola** [comment]
I'm closing this just because it's too old. We can open new issues for items that are still valid.

Most of these items were solved already or replaced by new strategies (like hooks)
