### ISSUE TITLE
Meteor 1.6 "Class extends value undefined is not a constructor or null"

### ISSUE THREAD

**Issue by TheWaffleDimension** [meteor/react-packages#244]
I'm attempting to get this setup with Flow Router, and am running into this error:
```
/home/thewaffledimension/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Class extends value undefined is not a constructor or null
    at ReactMeteorData.jsx (packages/react-meteor-data/ReactMeteorData.jsx:164:40)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at createContainer.jsx (packages/react-meteor-data/createContainer.jsx:1:210)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:1:14)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /home/thewaffledimension/projects/web/react-app/.meteor/local/build/programs/server/packages/react-meteor-data.js:332:15
Exited with code: 1
```

**Comment by TheWaffleDimension** [comment]
Thanks @crapthings . Not sure why it wasn't working before, but copying and pasting your code in and modifying it to fit my application made it work.
