### ISSUE TITLE
[version 1.6.1.1] TypeError: Class extends value undefined is not a constructor or null at ReactMeteorData.jsx (packages/react-meteor-data/ReactMeteorData.js x:164:40)

### ISSUE THREAD

**Issue by chip** [meteor/react-packages#255]
Hi, Thanks in advance for creating these packages and for any suggestions.

I received this error on Meteor 1.3, so I decided to upgrade to **1.6.1.1** and am still having issues:
```
W20180523-11:21:37.215(-5)? (STDERR) /Users/chip/.meteor/packages/meteor-tool/.1.6.1_1.1hnw4g8++os.os[11/4608]
web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180523-11:21:37.216(-5)? (STDERR)                                            throw(ex);
W20180523-11:21:37.216(-5)? (STDERR)                                            ^                             
W20180523-11:21:37.216(-5)? (STDERR) 
W20180523-11:21:37.217(-5)? (STDERR) TypeError: Class extends value undefined is not a constructor or null
W20180523-11:21:37.217(-5)? (STDERR)     at ReactMeteorData.jsx (packages/react-meteor-data/ReactMeteorData.jsx:164:40)                                                                              
W20180523-11:21:37.217(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180523-11:21:37.218(-5)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180523-11:21:37.218(-5)? (STDERR)     at createContainer.jsx (packages/react-meteor-data/createContainer.jsx:1:210)
W20180523-11:21:37.218(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180523-11:21:37.218(-5)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180523-11:21:37.219(-5)? (STDERR)     at react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:1:139)
W20180523-11:21:37.219(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180523-11:21:37.219(-5)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180523-11:21:37.220(-5)? (STDERR)     at /Users/chip/code/tracker-app/.meteor/local/build/programs/server/packages/react-meteor-data.js:330:15
W20180523-11:21:37.220(-5)? (STDERR)     at /Users/chip/code/tracker-app/.meteor/local/build/programs/server/packages/react-meteor-data.js:337:3
W20180523-11:21:37.220(-5)? (STDERR)     at /Users/chip/code/tracker-app/.meteor/local/build/programs/server/boot.js:411:36
W20180523-11:21:37.220(-5)? (STDERR)     at Array.forEach (<anonymous>)
W20180523-11:21:37.220(-5)? (STDERR)     at /Users/chip/code/tracker-app/.meteor/local/build/programs/server/boot.js:220:19
W20180523-11:21:37.221(-5)? (STDERR)     at /Users/chip/code/tracker-app/.meteor/local/build/programs/server/boot.js:471:5
W20180523-11:21:37.221(-5)? (STDERR)     at Function.run (/Users/chip/code/tracker-app/.meteor/local/build/programs/server/profile.js:510:12)
```

Here's the output from **meteor list**:
```
accounts-base                           1.4.2  A user account system
accounts-password                       1.5.1  Password support for accounts
alanning:roles                          1.2.16  Authorization package for Meteor
aldeed:collection2                      2.10.0* Automatic validation of inser...
aldeed:geocoder                         0.3.8  Easy geocoding by way of the n...
audit-argument-checks                   1.0.7  Try to detect inadequate input...
browser-policy                          1.1.0  Configure security policies en...
cfs:graphicsmagick                      0.0.18  Adds `gm` to scope with the a...
cfs:gridfs                              0.0.34  GridFS storage adapter for Co...
cfs:s3                                  0.1.3  Amazon Web Services S3 storage...
cfs:standard-packages                   0.5.10  Filesystem for Meteor, collec...
cfs:ui                                  0.1.3  CollectionFS, provides UI helpers
check                                   1.3.1  Check whether a value matches ...
cordova:cordova-plugin-statusbar        2.1.2
cordova:phonegap-plugin-barcodescanner  4.1.0
dburles:google-maps                     1.1.5  Google Maps Javascript API v3
digilord:faker                          1.0.7  Faker.js packaged for Meteor. ...
dynamic-import                          0.3.0  Runtime support for Meteor 1.5...
ecmascript                              0.10.8  Compiler plugin that supports...
email                                   1.2.3  Send email messages
fastclick                               1.0.13  Faster touch events on mobile
fourseven:scss                          3.13.0* Style with attitude. Sass and...
harrison:papa-parse                     1.1.7  A powerful, in-browser CSV par...
jquery                                  1.11.11  Manipulate the DOM using CSS...
kadira:blaze-layout                     2.3.0  Layout Manager for Blaze (work...
kadira:debug                            3.2.2  Full Stack Debugging Solution ...
kadira:flow-router                      2.12.1  Carefully Designed Client Sid...
kadira:react-layout                     1.5.3  Layout Manager for React with ...
launch-screen                           1.1.1  Default and customizable launc...
mdg:camera                              1.4.1  Photos with one function call ...
mdg:reload-on-resume                    1.0.4  On Cordova, only allow the app...
meteor-base                             1.3.0  Packages that every Meteor app...
meteorhacks:fast-render                 2.16.0  Render your app before the DD...
meteorhacks:ssr                         2.2.0  Server Side Rendering for Mete...
mikowals:batch-insert                   1.1.14  Insert multiple documents to ...
mobile-status-bar                       1.0.14  Good defaults for the mobile ...
momentjs:moment                         2.22.1  Moment.js (official): parse, ...
nourharidy:ssl                          0.2.2  Sexy SSL support for Meteor
npm-container                           1.2.0+ Contains all your npm dependen...
pcjpcj2:ratchet                         2.0.2   Ratchet UI Framework for Meteor
pfafman:filesaver                       0.2.3_2* filesaver.js packaged for us...
practicalmeteor:mocha                   2.4.5_6  Write package tests with moc...
random                                  1.1.0  Random number generator and ut...
react-meteor-data                       0.2.16  React higher-order component ...
react-runtime                           0.14.3* Facebook's React library
reactive-dict                           1.2.0  Reactive dictionary
reactive-var                            1.0.11  Reactive variable
session                                 1.1.7  Session variable
shell-server                            0.3.1  Server-side component of the `...
standard-minifier-css                   1.4.1  Standard css minifier used wit...
standard-minifier-js                    2.3.4  Standard javascript minifiers ...
stevezhu:lodash                         4.17.2  A utility library delivering ...
templating                              1.3.2  Allows templates to be defined...
themeteorchef:bert                      2.1.1* A client side, multi-style ale...
themeteorchef:jquery-validation         1.14.0  jQuery Validation by jzaeffer...
tracker                                 1.1.3  Dependency tracker to allow re...
twbs:bootstrap                          3.3.6  The most popular front-end fra...


* New versions of these packages are available! Run 'meteor update' to try to
  update those packages to their latest versions. If your packages cannot be
  updated further, try typing `meteor add <package>@<newVersion>` to see more
  information.

+ These packages are built locally from source.
```

Here's **.meteor/corova-plugins**
```
cordova-plugin-statusbar@2.1.2
phonegap-plugin-barcodescanner@4.1.0
```

**meteor node --version**: v8.11.1
**meteor npm --version**: 5.6.0

I've commented in #244, and tried the suggestions to no avail. Since that issue is closed with few participants, I decided to cast a wider net here. Please let me know if additional info is needed. Thanks again.

**Comment by mshvern** [comment]
I'm having the same issue

**Comment by zzzzasd** [comment]
I'm having the same issue as well. Please help

**Comment by dburles** [comment]
Hey guys try updating React to the latest version

**Comment by zzzzasd** [comment]
I am running the latest version of react@16.4.2. Still doesn't work. Please and thanks for your help @dburles

**Comment by nimmi26** [comment]
Hello there

I have the same issue.
This issue occurs with package "react-meteor-data".
When I remove this package error has gone.

**Comment by squader** [comment]
I can confirm the issue, using Meteor 1.7.0.5 and 

"react": "^16.4.2",
"react-dom": "^16.4.2"

The issue occurs on a fresh project after adding react-meteor-data:

```
W20180827-13:19:56.846(2)? (STDERR) TypeError: Class extends value undefined is not a constructor or null
W20180827-13:19:56.846(2)? (STDERR)     at ReactMeteorData.jsx (packages/react-meteor-data/ReactMeteorData.jsx:162:36)
W20180827-13:19:56.846(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180827-13:19:56.846(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180827-13:19:56.847(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180827-13:19:56.847(2)? (STDERR)     at createContainer.jsx (packages/react-meteor-data/createContainer.jsx:1:210)
W20180827-13:19:56.847(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180827-13:19:56.847(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180827-13:19:56.848(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180827-13:19:56.848(2)? (STDERR)     at react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:1:139)
W20180827-13:19:56.848(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180827-13:19:56.848(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180827-13:19:56.849(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180827-13:19:56.849(2)? (STDERR)     at /Users/safran/Desktop/simple-todos/.meteor/local/build/programs/server/packages/react-meteor-data.js:330:15
W20180827-13:19:56.849(2)? (STDERR)     at /Users/safran/Desktop/simple-todos/.meteor/local/build/programs/server/packages/react-meteor-data.js:337:3
W20180827-13:19:56.850(2)? (STDERR)     at /Users/safran/Desktop/simple-todos/.meteor/local/build/programs/server/boot.js:411:36
W20180827-13:19:56.850(2)? (STDERR)     at Array.forEach (<anonymous>)
````

**Comment by dburles** [comment]
Guys I can't reproduce the issue (1.7.0.5), the steps were:

`meteor create test-project`
`meteor add react-meteor-data`
`npm i react react-dom`
`meteor`

@sfreiberg did you do anything different in your repro?

**Comment by abernix** [comment]
@sfrnqdr @zzzzasd @nimmi26 A full, cloneable reproduction which demonstrates the problem would be super helpful!

**Comment by norain2050** [comment]
I'm having the same issue
@abernix 

meteor@1.7.0.5 +react@0.14.9

 meteor add react-meteor-data@0.2.16
…



//LoginsContainersForMaterial.js
import React from 'react';
import {Meteor} from 'meteor/meteor';
import {render} from 'react-dom';
import {withTracker} from 'meteor/react-meteor-data';

const Logins=(props) => (
      <div>
        <div>
          <div className="logo">
             <img src='/img/logo.svg'/>
          </div>
          <div className="both"></div>
        </div>
        <div className="main">
        {props.main}
        </div>
      </div>
	);

const LoginsContainersForMaterial = withTracker(props => {
	return{
	};
})(Logins);


export default LoginsContainersForMaterial;


….


**********************************************

meteor


WARNING: npm peer requirements not installed:
W20181118-20:19:04.973(8)? (STDERR)  - react-addons-transition-group@0.14.x not installed.
W20181118-20:19:04.974(8)? (STDERR)  - react-addons-css-transition-group@0.14.x not installed.
W20181118-20:19:04.974(8)? (STDERR)  - react-addons-linked-state-mixin@0.14.x not installed.
W20181118-20:19:04.974(8)? (STDERR)  - react-addons-create-fragment@0.14.x not installed.
W20181118-20:19:04.974(8)? (STDERR)  - react-addons-update@0.14.x not installed.
W20181118-20:19:04.975(8)? (STDERR)  - react-addons-pure-render-mixin@0.14.x not installed.
W20181118-20:19:04.975(8)? (STDERR)  - react-addons-test-utils@0.14.x not installed.
W20181118-20:19:04.975(8)? (STDERR)  - react-addons-perf@0.14.x not installed.
W20181118-20:19:04.976(8)? (STDERR) 
W20181118-20:19:04.976(8)? (STDERR) Read more about installing npm peer dependencies:
W20181118-20:19:04.976(8)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20181118-20:19:04.976(8)? (STDERR) 
W20181118-20:19:05.063(8)? (STDERR) /Users/xinyiba/.meteor/packages/meteor-tool/.1.7.0_5.19pr45f.7esr++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20181118-20:19:05.063(8)? (STDERR) 						throw(ex);
W20181118-20:19:05.064(8)? (STDERR) 						^
W20181118-20:19:05.064(8)? (STDERR) 
W20181118-20:19:05.064(8)? (STDERR) Error: Cannot find module 'react-addons-transition-group'
W20181118-20:19:05.065(8)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)



*******************************************************


meteor npm install —save react-addons-transition-group@0.14.8 react-addons-css-transition-group@0.14.8 react-addons-linked-state-mixin@0.14.8 react-addons-create-fragment@0.14.8 react-addons-update@0.14.8  react-addons-pure-render-mixin@0.14.8 react-addons-test-utils@0.14.8 react-addons-perf@0.14.8


meteor

/Users/xinyiba/.meteor/packages/meteor-tool/.1.7.0_5.19pr45f.7esr++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20181118-20:59:39.439(8)? (STDERR) 						throw(ex);
W20181118-20:59:39.440(8)? (STDERR) 						^
W20181118-20:59:39.440(8)? (STDERR) 
W20181118-20:59:39.440(8)? (STDERR) TypeError: Class extends value undefined is not a constructor or null
W20181118-20:59:39.440(8)? (STDERR)     at ReactMeteorData.jsx (packages/react-meteor-data/ReactMeteorData.jsx:164:40)
W20181118-20:59:39.441(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20181118-20:59:39.441(8)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20181118-20:59:39.441(8)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20181118-20:59:39.441(8)? (STDERR)     at createContainer.jsx (packages/react-meteor-data/createContainer.jsx:1:210)
W20181118-20:59:39.441(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20181118-20:59:39.442(8)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20181118-20:59:39.442(8)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20181118-20:59:39.442(8)? (STDERR)     at react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:1:139)
W20181118-20:59:39.442(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20181118-20:59:39.443(8)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20181118-20:59:39.443(8)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20181118-20:59:39.443(8)? (STDERR)     at /Users/xinyiba/myapp/dailishang/dailishangapp/.meteor/local/build/programs/server/packages/react-meteor-data.js:330:15
W20181118-20:59:39.443(8)? (STDERR)     at /Users/xinyiba/myapp/dailishang/dailishangapp/.meteor/local/build/programs/server/packages/react-meteor-data.js:337:3
W20181118-20:59:39.444(8)? (STDERR)     at /Users/xinyiba/myapp/dailishang/dailishangapp/.meteor/local/build/programs/server/boot.js:411:36
W20181118-20:59:39.444(8)? (STDERR)     at Array.forEach (<anonymous>)
