### ISSUE TITLE
Meteor 1.9 Minifier errors with react-meteor-data 2.0.1

### ISSUE THREAD

**Issue by paulincai** [meteor/react-packages#284]
Hi,

```
react-meteor-data*  upgraded from 0.2.16 to 2.0.1
```
Now I am not able to build the project. Going back to 0.2.16, everything is ok.

My Babel setup:

```
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-optional-chaining": "^7.8.3",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.8.3",
    "@babel/preset-env": "^7.8.4",
    "@babel/preset-react": "^7.8.3",
    "@babel/runtime": "^7.8.4",
    "babel-eslint": "^10.0.3",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-react-intl": "^5.1.18",
    "babel-plugin-transform-class-properties": "^6.24.1",
```

Errors as follows:
```
Errors prevented bundling:
While minifying app code:

/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63:
Unexpected token (1:8) while minifying
dynamic/node_modules/meteor/react-meteor-data/index.js
at Object.raise
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63)
at Object.unexpected
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/util.js:160:16)
at Object.parseIdentifierName
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/expression.js:2160:18)
at Object.parseIdentifier
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/expression.js:2127:23)
at Object.parseFunctionId
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:1095:52)
at Object.parseFunction
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:1047:22)
at Object.parseFunctionStatement
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:555:17)
at Object.parseStatementContent
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:185:21)
at Object.parseStatement
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:141:17)
at Object.parseStatement
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/plugins/flow.js:1675:28)
at Object.parseBlockOrModuleBlockBody
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:860:25)
at Object.parseBlockBody
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:836:10)
at Object.parseTopLevel
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:47:10)
at Object.parseTopLevel
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/plugins/flow.js:2913:30)
at Object.parse
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/index.js:43:10)
at Object.parse
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/index.js:58:38)
at parse
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/parser.js:7:22)
at Object.minify
(/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0.c3zoas.a8gs7++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:184:5)
at Object.minify (packages/babel-compiler.js:59:29)
at meteorJsMinify (packages/minifier-js.js:60:25)
at packages/minifyStdJS/plugin/minify-js.js:126:20
at Array.forEach (<anonymous>)
at MeteorBabelMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:118:9)

```

**Comment by filipenevola** [comment]
Hi @paulincai, is this issue still affecting you?

If so, please respond here and then we can proceed analyzing it.

**Comment by paulincai** [comment]
Hi @filipenevola , thanks for following up. I am running react-meteor-data@2.2.1 with Meteor 2.0 with absolutely no problem.
