### ISSUE TITLE
Can not add the react package on windows?

### ISSUE THREAD

**Issue by HenrikGr** [meteor/react-packages#39]
Using Meteor version 1.2.2

**Comment by bunderhi** [comment]
The error seems specific to the jsx package

**Comment by ihistand** [comment]
Reproduced this error in Win 8.1, Node 0.12.5, Meteor 1.1.0.2   Here's the error:

````
PS C:\Users\Ivan\OneDrive\Projects\PCI-React> meteor add react
meteor : 
At line:1 char:1
+ meteor add react
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                        throw(ex);
                              ^
TypeError: Cannot call method 'replace' of null
    at convert (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:49:15)
    at convertBySchema (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:18:12)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:42:18
    at Function._.each._.forEach 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at convertBySchema (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:40:5)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:32:14
    at Array.map (native)
    at Function._.map._.collect 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:98:56)
    at convertBySchema (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:31:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:42:18
    at Function._.each._.forEach 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at convertBySchema (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:40:5)
    at Object.exports.convertJSImage (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\colon-converter.js:88:10)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:120:44
    at Array.forEach (native)
    at Function._.each._.forEach 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Object.exports._extractAndConvert (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:111:7)
    at [object Object]._.extend._downloadBuildToTempDir 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:295:20)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:462:37
    at Array.forEach (native)
    at Function._.each._.forEach 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:460:11
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at Object.down
load (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:419:20)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:553:22
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:550:20)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:668:25
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:667:20
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\catalog.js:100:5
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\Users\Ivan\AppData\Local\.meteor\packages\me
teor-tool\1.1.3\mt-os.windows.x86_32\tools\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:666:13)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:238:35
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:228:18)
    at ProjectContext._.extend.saveChangedMetadata 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:216:10)
    at ProjectContext._.extend.prepareProjectForBuild 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:221:10)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\commands-packages.js:1878:20
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Command.main.registerCommand.name [as func] 
(C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\commands-packages.js:1877:27)
    at C:\Users\Ivan\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\main.js:1363:23
````

**Comment by hypernova0** [comment]
Us window users must be a pretty small minority eh? I really want to start using the official react package and react router :/

**Comment by stubailo** [comment]
@hypernova0 as I mentioned on another issue, we just started a new sprint working through these issues - I expect it will be fixed very soon; we can't commit to fixing issues in less than 4 days :]

**Comment by tnedich** [comment]
Same problem here. Windows 7 Ultimate 64-bit Node v0.12.4.

**Comment by KamuelaFranco** [comment]
Same issue on Windows 10 preview 64-bit latest version of Node. Thanks @stubailo for keeping up with this.

**Comment by ignatovar** [comment]
Same here! Appreciate all the effort you are investing!

**Comment by ArsalanDotMe** [comment]
Does someone have a workaround for this while this is being fixed?

**Comment by skyrack2** [comment]
Thank goodness Meteor and Webix works...
Seems like a very slow reaction to fix this issue.

**Comment by avital** [comment]
I tracked down the issue to the fact that the `jsx` package was published from a Git checkout of Meteor rather than from a Meteor release. This is a bug in the meteor tool, but in the meanwhile I re-released the package from a Meteor release, so this should be working now.

**Comment by skyrack2** [comment]
Many thanks,

Will try this now.

**Comment by skyrack2** [comment]
So far, so good...

**Comment by stubailo** [comment]
Awesome! I'm really glad we tracked this down.

**Comment by hypernova0** [comment]
+1 thanks

**Comment by puruzio** [comment]
I just tried "meteor add react" but it still fails with the same error message. Am I doing it wrong?

**Comment by jaypanares** [comment]
@avital Package working well (doing the tutorial so far), but encountered an error when I added the package.  I re-ran the add package command and it installed successfully.  Error I received below:

```
> meteor add react
   Downloading 9 packages                    -
C:\Users\Jay\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:643
      Console.debug(err);
      ^
ReferenceError: Console is not defined
    at Object._onImmediate (C:\Users\Jay\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:643:7)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

Jay@JAYPANARES-PC D:\Development\meteor\play\simple-todos-react
> meteor add react

Changes to your project's package version selections:

babel-compiler      added, version 5.7.3
babel-runtime       added, version 0.1.2
coffeescript        added, version 1.0.6
cosmos:browserify   added, version 0.4.0
jsx                 added, version 0.1.3
react               added, version 0.1.3
react-meteor-data   added, version 0.1.1
react-runtime       added, version 0.13.3_2
react-runtime-dev   added, version 0.13.3_2
react-runtime-prod  added, version 0.13.3_1


react: Everything you need to use React with Meteor.
```

Using Windows 8.1
